#!/usr/bin/env bash

# do all of this only if running interactively
[[ $- == *i* ]] || return

# enable programmable completion features
[ -f /etc/bash_completion ] && . /etc/bash_completion

# history stuff
HISTCONTROL=erasedups:ignoredups:ignorespace
HISTFILESIZE=100000
HISTSIZE=10000
bind '"\eOA": history-search-backward'
bind '"\e[A": history-search-backward'
bind '"\eOB": history-search-forward'
bind '"\e[B": history-search-forward'
shopt -s histappend

# less stuff
export LESS=-Ri

# ls stuff
alias ls='ls -Ah --color=auto'
export LS_COLORS='di=1;34:ln=1;35:so=1;32:pi=1;33:ex=1;31:bd=1;36:cd=1;36:su=1;31:sg=1;31:tw=1;34:ow=1;34'

# editor stuff
alias vi=nvim
export EDITOR=nvim

# xclip default clipboard
alias xclip='xclip -selection clipboard'

# interactive file ops
alias rm='rm --interactive=once'
alias cp='cp --interactive'
alias mv='mv --interactive'
alias rclone-sync='rclone sync --create-empty-src-dirs --interactive'

# fff
export FFF_FAV1="$HOME"/Downloads
export FFF_FAV2=/media/ted15/music
# https://github.com/dylanaraps/fff/issues/180
export FFF_KEY_BULK_RENAME="off"
export FFF_KEY_BULK_RENAME_ALL="off"

# set prompt
source "$HOME"/bin/git-prompt.sh
PS1="\[\033[1m\]\[\033[32m\][\u@\h:\w\$(__git_ps1 '@%s')]\$ \[\033[0m\]"
